#pragma once

#include <atomic>
#include <chrono>
#include <cstdint>
#include <thread>
#include <fmt/format.h>
#include "RingBuffer.h"
#include "LoadConfiguration.h"
#include "LogRecord.h"

/**
 * @brief Formats a raw log string with a timestamp, log level, and the actual message.
 *
 * @param ts The exact point in time when the log event occurred, captured via system clock.
 * @param level The severity level of the log.
 * @param msg The raw or pre-formatted log message payload.
 * @return A fully formatted string ready to be written to standard output or a file.
 */
std::string FormatLogLine(std::chrono::system_clock::time_point ts, LogLevel level, std::string_view msg);

/**
 * @brief High-performance asynchronous logger designed to offload I/O operations from the critical path.
 *
 * @details This logger utilizes a pre-allocated `RingBuffer` to achieve zero-allocation logging
 * on the hot path. If producer threads generate logs faster than the background consumer thread
 * can flush them to disk, new records are dropped to guarantee that real-time execution threads
 * are never blocked.
 */
class AsyncLogger {
public:
    /**
     * @brief Constructs the asynchronous logger with specific memory and flushing constraints.
     *
     * @param maxMessageChars Maximum number of characters allowed per log message.
     * @param queueCapacity Maximum number of pending LogRecord elements in the ring buffer.
     * @param flushIntervalMs Time in milliseconds between periodic forced flushes to disk.
     * @param notifyThreshold Number of messages accumulated before waking up the consumer thread.
     */
    AsyncLogger(size_t maxMessageChars, size_t queueCapacity, size_t flushIntervalMs, size_t notifyThreshold);

    /**
     * @brief Destructor. Ensures the background thread is safely stopped and pending logs are flushed.
     */
    ~AsyncLogger();

    // Disable copy semantics to guarantee singleton/unique resource ownership behavior.
    AsyncLogger(const AsyncLogger&) = delete;
    AsyncLogger& operator=(const AsyncLogger&) = delete;

    /**
     * @brief Spawns the background consumer thread and begins processing the ring buffer.
     */
    void Start();

    /**
     * @brief Signals the background thread to stop, flushes remaining logs, and joins the thread.
     */
    void Stop();

    /**
     * @brief Retrieves the total number of log messages dropped due to a full ring buffer.
     *
     * @return The number of dropped logs since the logger was started.
     */
    uint64_t DroppedCount();

    /**
     * @brief Template wrapper that packs variadic arguments and forwards them to the type-erased Write method.
     *
     * @tparam Args Variadic template arguments for format string parameters.
     * @param level Severity level of the log message.
     * @param fmtStr The compile-time checked format string (e.g., "Value: {}").
     * @param args The arguments to inject into the format string.
     */
    template <typename... Args>
    void Log(LogLevel level, fmt::format_string<Args...> fmtStr, Args&&... args)
    {
        Write(level, fmtStr, fmt::make_format_args(args...));
    }

    /**
     * @brief Core logging method utilizing type-erased format arguments to prevent template bloat.
     *
     * @details Attempts to acquire a slot in the RingBuffer. If successful, the timestamp is captured
     * and the formatted payload is written into the `LogRecord`. If the buffer is full, the drop counter
     * is incremented and it returns immediately.
     *
     * @param level Severity level of the log message.
     * @param fmtStr The format string view.
     * @param args Type-erased arguments generated by `fmt::make_format_args`.
     */
    void Write(LogLevel level, fmt::string_view fmtStr, fmt::format_args args);

private:
    /**
     * @brief The main loop executed by the background consumer thread.
     *
     * @details Continuously polls or waits on the ring buffer, extracting records and writing them
     * to the destination (console/file) based on `flushIntervalMs` and `notifyThreshold`.
     */
    void ConsumerLoop();

    /**
     * @brief Writes a single formatted record to the final output destination.
     *
     * @param record The populated log record extracted from the ring buffer.
     */
    void WriteRecord(const LogRecord& record);

    size_t maxMessageChars;   ///< Max characters per log.
    size_t queueCapacity;     ///< Maximum elements the ring buffer can hold.
    size_t flushIntervalMs;   ///< Milliseconds before forcing a stream flush.
    size_t notifyThreshold;   ///< Queue threshold to trigger a consumer wake-up.

    RingBuffer<LogRecord> queue; ///< Lock-free or low-contention ring buffer holding pending log records.

    std::thread consumer;               ///< Background thread executing `ConsumerLoop`.
    std::atomic<bool> running{ false }; ///< Atomic flag controlling the consumer loop execution.
    std::atomic<uint64_t> dropped{ 0 }; ///< Atomic counter tracking logs dropped due to ring buffer overflow.
};

/**
 * @brief Global namespace providing a lightweight, globally accessible interface for logging.
 */
namespace Log {
    /**
     * @brief Internal namespace hiding implementation details from the public API.
     */
    namespace detail {
        /**
         * @brief Routes the log payload to the global logger instance using type-erased arguments.
         *
         * @param level Severity level.
         * @param fmtStr Format string view.
         * @param args Type-erased format arguments.
         */
        void Dispatch(LogLevel level, fmt::string_view fmtStr, fmt::format_args args);
    }

    /**
     * @brief Logs an informational message.
     *
     * @tparam Args Variadic template arguments.
     * @param f Format string.
     * @param a Arguments for the format string.
     */
    template <typename... Args>
    void Info(fmt::format_string<Args...> f, Args&&... a)
    {
        detail::Dispatch(LogLevel::Info, f, fmt::make_format_args(a...));
    }

    /**
     * @brief Logs a warning message.
     *
     * @tparam Args Variadic template arguments.
     * @param f Format string.
     * @param a Arguments for the format string.
     */
    template <typename... Args>
    void Warning(fmt::format_string<Args...> f, Args&&... a)
    {
        detail::Dispatch(LogLevel::Warning, f, fmt::make_format_args(a...));
    }

    /**
     * @brief Logs an error message.
     *
     * @tparam Args Variadic template arguments.
     * @param f Format string.
     * @param a Arguments for the format string.
     */
    template <typename... Args>
    void Error(fmt::format_string<Args...> f, Args&&... a)
    {
        detail::Dispatch(LogLevel::Error, f, fmt::make_format_args(a...));
    }
}