#pragma once

#include <atomic>

#include "AppConfig.h"
#include "OrtSession.h"
#include "PipelineSlot.h"
#include "PerformanceMetrics.h"
#include "RawFrame.h"
#include "ResultSink.h"
#include "RingBuffer.h"

/**
 * @file Stages.h
 * @brief Reentrant thread-body functions defining the core stages of the inference pipeline.
 *
 * @details Each function encapsulates the infinite loop of a dedicated worker thread.
 * They are strictly reentrant: there is no mutable shared state aside from the thread-safe
 * queues (RingBuffers), pre-allocated pools, indexed session arrays, and atomic metrics.
 *
 * **Scaling Model:** Because they are stateless, you can safely launch N concurrent copies
 * of any stage (e.g., 4 Prep threads, 2 Infer threads) based on application configuration
 * to perfectly saturate the CPU and GPU.
 *
 * **Zero-Allocation Hot Path:** Scratch buffers (like resizing matrices or intermediate
 * float buffers) are allocated EXACTLY ONCE at the top of the function, before entering
 * the `while` loop. They are reused for the entire lifetime of the thread.
 */

 /**
  * @brief Executes the Preprocessing stage: converts raw image patches into NCHW floating-point blobs.
  *
  * @details For every patch in the `RawFrame`, this stage performs:
  * 1. Resizing (using the precomputed `AntialiasResizer`). This is a zero-cost identity
  *    passthrough if the patch and model dimensions match (the resizer safely aliases the source).
  * 2. Fused conversion from interleaved BGR to planar Float (NCHW), applying the scale and
  *    offset bounds defined by the model's `ContractMetadata`.
  *
  * **Lifecycle Note:** The `RawFrame` is released back to its pool the instant the transformation
  * finishes. This keeps the hold time on the camera/IPC buffers as short as possible, preventing
  * upstream frame drops.
  *
  * @param cfg Global application configuration.
  * @param session The session configuration providing the geometric constraints.
  * @param qRaw Incoming queue of captured raw frames.
  * @param rawPool Pool to return the raw frames to once pixel data is extracted.
  * @param slotPool Pool of empty `PipelineSlot`s ready to be filled with preprocessed data.
  * @param qPrep Outgoing queue of populated slots ready for GPU inference.
  * @param metrics Telemetry tracker for latency measurement.
  */
void PrepStage(const AppConfig& cfg,
    const OrtSessionConfig& session,
    RingBuffer<RawFrame*>& qRaw,
    RingBuffer<RawFrame*>& rawPool,
    RingBuffer<PipelineSlot*>& slotPool,
    RingBuffer<PipelineSlot*>& qPrep,
    PerformanceMetrics& metrics);

/**
 * @brief Executes the Inference stage: manages GPU memory transfers and neural network execution.
 *
 * @details Acts as the orchestrator for the `OrtSessionConfig`. It handles the Host-To-Device (H2D)
 * transfer of the input tensor, the ONNX/TensorRT execution, and the Device-To-Host (D2H)
 * transfer of the classification scores and raw segmentation maps.
 *
 * **Thread Safety:** `OrtSessionConfig::RunBatch` is NOT thread-safe. Therefore, if you launch
 * multiple inference threads, each thread MUST receive its own exclusive, isolated `OrtSessionConfig`
 * instance.
 *
 * @param session The exclusive ONNX Runtime session bound to this specific thread.
 * @param qPrep Incoming queue of preprocessed `PipelineSlot`s.
 * @param qInf Outgoing queue of inferred `PipelineSlot`s ready for post-processing.
 * @param slotPool Target pool in case of early rejection/error (to prevent leaks).
 * @param metrics Telemetry tracker for latency measurement.
 */
void InferStage(OrtSessionConfig& session,
    RingBuffer<PipelineSlot*>& qPrep,
    RingBuffer<PipelineSlot*>& qInf,
    RingBuffer<PipelineSlot*>& slotPool,
    PerformanceMetrics& metrics);

/**
 * @brief Executes the Post-processing stage: normalizes maps, applies thresholds, and publishes results.
 *
 * @details Transforms the raw floating-point logits generated by the network into actionable data:
 * 1. Normalizes the output map using the Min/Max bounds from the model contract.
 * 2. Applies the classification score threshold.
 * 3. Generates a binary mask (if enabled).
 * 4. Pushes the final payload to the `IResultSink` (e.g., UI rendering or disk logging).
 *
 * **CRITICAL PIPELINE INTEGRITY:**
 * This is the ONLY stage responsible for returning the `PipelineSlot` back to the `slotPool`.
 * This return MUST be guaranteed using an RAII Scope Guard. If an exception is thrown during
 * post-processing and the slot is skipped, the pool will eventually exhaust its capacity,
 * causing the entire pipeline to stall silently with no obvious error message.
 *
 * @param cfg Global application configuration.
 * @param session The session configuration providing the geometric and contract bounds.
 * @param qInf Incoming queue of inferred `PipelineSlot`s.
 * @param slotPool The pool where the processed slot must be returned.
 * @param sink The destination interface for the finalized analysis data.
 * @param metrics Telemetry tracker for latency measurement.
 */
void PostStage(const AppConfig& cfg,
    const OrtSessionConfig& session,
    RingBuffer<PipelineSlot*>& qInf,
    RingBuffer<PipelineSlot*>& slotPool,
    IResultSink& sink,
    PerformanceMetrics& metrics);